import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const mulsih = Mulish({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MonyVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${mulsih.variable} antialiased`}>{children}</body>
    </html>
  );
}
